# Sumpy thus far is poorly parallelized (no workgroup-level parallelism), and
# the Kepler has a tendency to hang as a result.
#
# Python 3.5 K40:
#   script:
#   - export PY_EXE=python3.5
#   - export PYOPENCL_TEST=nvi:k40
#   - export EXTRA_INSTALL="numpy mako"
#   - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
#   - ". ./build-and-test-py-project.sh"
#   tags:
#   - python3.5
#   - nvidia-k40
#   except:
#   - tags
#  artifacts:
#    reports:
#      junit: test/pytest.xml

Python 3 POCL:
  script:
  - export PY_EXE=python3
  - export PYOPENCL_TEST=portable:pthread
  - export EXTRA_INSTALL="pybind11 numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3
  - pocl
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 3 Titan X:
  script:
  - py_version=3
  - export PYOPENCL_TEST=nvi:titan
  - EXTRA_INSTALL="pybind11 numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3
  - nvidia-titan-x
  except:
  - tags
  allow_failure: True
  artifacts:
    reports:
      junit: test/pytest.xml

Python 3 Conda:
  script:
  # Disable caching to ensure SymEngine code generation is exercised.
  - export SUMPY_NO_CACHE=1
  - export SUMPY_FORCE_SYMBOLIC_BACKEND=symengine
  - export PYOPENCL_TEST=portable:pthread
  - CONDA_ENVIRONMENT=.test-conda-env-py3.yml
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project-within-miniconda.sh
  - ". ./build-and-test-py-project-within-miniconda.sh"
  tags:
  - porter
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 3.6 POCL Titan X:
  script:
  # Disable caching to ensure SymEngine code generation is exercised.
  - export SUMPY_NO_CACHE=1
  - export SUMPY_FORCE_SYMBOLIC_BACKEND=symengine
  - export PYOPENCL_TEST=portable:titan
  - CONDA_ENVIRONMENT=.test-conda-env-py3.yml
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project-within-miniconda.sh
  - ". ./build-and-test-py-project-within-miniconda.sh"
  tags:
  - nvidia-titan-x
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Documentation:
  script:
  - EXTRA_INSTALL="pybind11 numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-docs.sh
  - ". ./build-docs.sh"
  tags:
  - python3

Flake8:
  script:
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
  - . ./prepare-and-run-flake8.sh "$CI_PROJECT_NAME" test examples
  tags:
  - python3
  except:
  - tags

# https://github.com/illinois-scicomp/machine-shop-maintenance/issues/4
# Benchmarks:
#   script:
#   - CONDA_ENVIRONMENT=.test-conda-env-py3.yml
#   - PROJECT=sumpy
#   - PYOPENCL_TEST=portable:pthread
#   - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-benchmark-py-project.sh
#   - ". ./build-and-benchmark-py-project.sh"
#   tags:
#   - linux
#   - benchmark
#   except:
#   - tags
