Python 2.7 POCL:
  script:
  - export PY_EXE=python2.7
  - export PYOPENCL_TEST=portable
  - export EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - pocl
  except:
  - tags
Python 3.4 POCL:
  script:
  - export PY_EXE=python3.4
  - export PYOPENCL_TEST=portable
  - export EXTRA_INSTALL="numpy mako"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.4
  - pocl
  except:
  - tags
