name: test-conda-env-py3
channels:
- inducer
- conda-forge
- defaults
dependencies:
- git
- conda-forge::numpy
- conda-forge::sympy
- pocl
- islpy
- pyopencl
- python=3.7
- symengine=0.5.0
- python-symengine=0.5.0

# things not in here: loopy boxtree pymbolic pyfmmlib
# (see .test-conda-env-py3-requirements.txt)